services:
  backend:
    image: arcan1s/ahriman:edge
    privileged: true

    environment:
      AHRIMAN_DEBUG: yes
      AHRIMAN_OAUTH_CLIENT_ID: ${AHRIMAN_OAUTH_CLIENT_ID}
      AHRIMAN_OAUTH_CLIENT_SECRET: ${AHRIMAN_OAUTH_CLIENT_SECRET}
      AHRIMAN_OUTPUT: console
      AHRIMAN_PORT: 8080
      AHRIMAN_PRESETUP_COMMAND: sudo -u ahriman ahriman user-add ${AHRIMAN_OAUTH_USER} -R full -p ""
      AHRIMAN_REPOSITORY: ahriman-demo
      AHRIMAN_UNIX_SOCKET: /var/lib/ahriman/ahriman/ahriman.sock

    configs:
      - source: service
        target: /etc/ahriman.ini.d/99-settings.ini

    volumes:
      - type: volume
        source: repository
        target: /var/lib/ahriman
        volume:
          nocopy: true

    healthcheck:
      test: curl --fail --silent --output /dev/null http://backend:8080/api/v1/info
      interval: 10s
      start_period: 30s

    command: web

  frontend:
    image: nginx
    ports:
      - 8080:80

    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf

    volumes:
      - type: volume
        source: repository
        target: /srv
        read_only: true
        volume:
          nocopy: true

configs:
  nginx:
    file: nginx.conf
  service:
    file: service.ini

volumes:
  repository:
