[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "ahriman-tox-plugins"
classifiers = [
    "Framework :: tox",
]
version = "1"

[project.entry-points.tox]
dynamic-version = "dynamic_version"

[tool.hatch.build.targets.wheel]
packages = ["dynamic_version"]
