[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "ahriman-pytest-plugins"
classifiers = [
    "Framework :: Pytest",
]
version = "1"

[project.entry-points.pytest11]
ahriman-fixtures = "ahriman_fixtures"

[tool.hatch.build.targets.wheel]
packages = ["ahriman_fixtures"]
