services:
  volume-init:
    image: arcan1s/ahriman:edge
    user: root

    entrypoint: [
      "chown",
    ]
    command: [
      "ahriman:ahriman",
      "/var/lib/ahriman",
    ]

    volumes:
      - type: volume
        source: repository
        target: /var/lib/ahriman

  backend:
    image: arcan1s/ahriman:edge
    privileged: true

    environment:
      AHRIMAN_DEBUG: yes
      AHRIMAN_OUTPUT: console
      AHRIMAN_REPOSITORY: ahriman-demo

    volumes:
      - type: volume
        source: repository
        target: /var/lib/ahriman

    depends_on:
      volume-init:
        condition: service_completed_successfully

    command: repo-daemon

  frontend:
    image: nginx
    ports:
      - 8080:80

    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf

    volumes:
      - type: volume
        source: repository
        target: /srv
        read_only: true
        volume:
          nocopy: true

configs:
  nginx:
    file: nginx.conf

volumes:
  repository:
