.TH AHRIMAN "1" Manual
.SH NAME
ahriman
.SH SYNOPSIS
.B ahriman
[-h] [-a ARCHITECTURE] [-c CONFIGURATION] [--force] [-l LOCK] [--no-report] [-q] [--unsafe] [-v] {aur-search,search,help,help-commands-unsafe,key-import,package-add,add,package-update,package-remove,remove,package-status,status,package-status-remove,package-status-update,status-update,patch-add,patch-list,patch-remove,repo-backup,repo-check,check,repo-clean,clean,repo-config,config,repo-rebuild,rebuild,repo-remove-unknown,remove-unknown,repo-report,report,repo-restore,repo-setup,init,repo-init,setup,repo-sign,sign,repo-status-update,repo-sync,sync,repo-triggers,repo-update,update,user-add,user-list,user-remove,web} ...
.SH DESCRIPTION
ArcH Linux ReposItory MANager

.SH OPTIONS
.TP
\fB\-a\fR \fI\,ARCHITECTURE\/\fR, \fB\-\-architecture\fR \fI\,ARCHITECTURE\/\fR
target architectures (can be used multiple times)

.TP
\fB\-c\fR \fI\,CONFIGURATION\/\fR, \fB\-\-configuration\fR \fI\,CONFIGURATION\/\fR
configuration path

.TP
\fB\-\-force\fR
force run, remove file lock

.TP
\fB\-l\fR \fI\,LOCK\/\fR, \fB\-\-lock\fR \fI\,LOCK\/\fR
lock file

.TP
\fB\-\-no\-report\fR
force disable reporting to web service

.TP
\fB\-q\fR, \fB\-\-quiet\fR
force disable any logging

.TP
\fB\-\-unsafe\fR
allow to run ahriman as non\-ahriman user. Some actions might be unavailable

.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit

.SH
COMMAND
.TP
\fBahriman\fR \fI\,aur-search\/\fR
search for package
.TP
\fBahriman\fR \fI\,help\/\fR
show help message
.TP
\fBahriman\fR \fI\,help-commands-unsafe\/\fR
list unsafe commands
.TP
\fBahriman\fR \fI\,key-import\/\fR
import PGP key
.TP
\fBahriman\fR \fI\,package-add\/\fR
add package
.TP
\fBahriman\fR \fI\,package-remove\/\fR
remove package
.TP
\fBahriman\fR \fI\,package-status\/\fR
get package status
.TP
\fBahriman\fR \fI\,package-status-remove\/\fR
remove package status
.TP
\fBahriman\fR \fI\,package-status-update\/\fR
update package status
.TP
\fBahriman\fR \fI\,patch-add\/\fR
add patch set
.TP
\fBahriman\fR \fI\,patch-list\/\fR
list patch sets
.TP
\fBahriman\fR \fI\,patch-remove\/\fR
remove patch set
.TP
\fBahriman\fR \fI\,repo-backup\/\fR
backup repository data
.TP
\fBahriman\fR \fI\,repo-check\/\fR
check for updates
.TP
\fBahriman\fR \fI\,repo-clean\/\fR
clean local caches
.TP
\fBahriman\fR \fI\,repo-config\/\fR
dump configuration
.TP
\fBahriman\fR \fI\,repo-rebuild\/\fR
rebuild repository
.TP
\fBahriman\fR \fI\,repo-remove-unknown\/\fR
remove unknown packages
.TP
\fBahriman\fR \fI\,repo-report\/\fR
generate report
.TP
\fBahriman\fR \fI\,repo-restore\/\fR
restore repository data
.TP
\fBahriman\fR \fI\,repo-setup\/\fR
initial service configuration
.TP
\fBahriman\fR \fI\,repo-sign\/\fR
sign packages
.TP
\fBahriman\fR \fI\,repo-status-update\/\fR
update repository status
.TP
\fBahriman\fR \fI\,repo-sync\/\fR
sync repository
.TP
\fBahriman\fR \fI\,repo-triggers\/\fR
run triggers
.TP
\fBahriman\fR \fI\,repo-update\/\fR
update packages
.TP
\fBahriman\fR \fI\,user-add\/\fR
create or update user
.TP
\fBahriman\fR \fI\,user-list\/\fR
user known users and their access
.TP
\fBahriman\fR \fI\,user-remove\/\fR
remove user
.TP
\fBahriman\fR \fI\,web\/\fR
web server
.SH COMMAND \fI\,'ahriman aur-search'\/\fR
usage: ahriman aur-search [-h] [-e] [-i]
                          [--sort-by {description,first_submitted,id,last_modified,maintainer,name,num_votes,out_of_date,package_base,package_base_id,popularity,repository,url,url_path,version}]
                          search [search ...]

search for package in AUR using API

.TP
\fBsearch\fR
search terms, can be specified multiple times, result will match all terms

.SH OPTIONS \fI\,'ahriman aur-search'\/\fR
.TP
\fB\-e\fR, \fB\-\-exit\-code\fR
return non\-zero exit status if result is empty

.TP
\fB\-i\fR, \fB\-\-info\fR
show additional package information

.TP
\fB\-\-sort\-by\fR \fI\,{description,first_submitted,id,last_modified,maintainer,name,num_votes,out_of_date,package_base,package_base_id,popularity,repository,url,url_path,version}\/\fR
sort field by this field. In case if two packages have the same value of the specified field, they will be always sorted
by name

.SH COMMAND \fI\,'ahriman help'\/\fR
usage: ahriman help [-h] [command]

show help message for application or command and exit

.TP
\fBcommand\fR
show help message for specific command

.SH COMMAND \fI\,'ahriman help-commands-unsafe'\/\fR
usage: ahriman help-commands-unsafe [-h] [--command COMMAND]

list unsafe commands as defined in default args

.SH OPTIONS \fI\,'ahriman help-commands-unsafe'\/\fR
.TP
\fB\-\-command\fR \fI\,COMMAND\/\fR
instead of showing commands, just test command line for unsafe subcommand and return 0 in case if command is safe and 1
otherwise

.SH COMMAND \fI\,'ahriman key-import'\/\fR
usage: ahriman key-import [-h] [--key-server KEY_SERVER] key

import PGP key from public sources to the repository user

.TP
\fBkey\fR
PGP key to import from public server

.SH OPTIONS \fI\,'ahriman key-import'\/\fR
.TP
\fB\-\-key\-server\fR \fI\,KEY_SERVER\/\fR
key server for key import

.SH COMMAND \fI\,'ahriman package-add'\/\fR
usage: ahriman package-add [-h] [-e] [-n]
                           [-s {PackageSource.Auto,PackageSource.Archive,PackageSource.AUR,PackageSource.Directory,PackageSource.Local,PackageSource.Remote,PackageSource.Repository}]
                           [--without-dependencies]
                           package [package ...]

add existing or new package to the build queue

.TP
\fBpackage\fR
package source (base name, path to local files, remote URL)

.SH OPTIONS \fI\,'ahriman package-add'\/\fR
.TP
\fB\-e\fR, \fB\-\-exit\-code\fR
return non\-zero exit status if result is empty

.TP
\fB\-n\fR, \fB\-\-now\fR
run update function after

.TP
\fB\-s\fR \fI\,{PackageSource.Auto,PackageSource.Archive,PackageSource.AUR,PackageSource.Directory,PackageSource.Local,PackageSource.Remote,PackageSource.Repository}\/\fR, \fB\-\-source\fR \fI\,{PackageSource.Auto,PackageSource.Archive,PackageSource.AUR,PackageSource.Directory,PackageSource.Local,PackageSource.Remote,PackageSource.Repository}\/\fR
explicitly specify the package source for this command

.TP
\fB\-\-without\-dependencies\fR
do not add dependencies

.SH COMMAND \fI\,'ahriman package-remove'\/\fR
usage: ahriman package-remove [-h] package [package ...]

remove package from the repository

.TP
\fBpackage\fR
package name or base

.SH COMMAND \fI\,'ahriman package-status'\/\fR
usage: ahriman package-status [-h] [--ahriman] [-e] [-i]
                              [-s {BuildStatusEnum.Unknown,BuildStatusEnum.Pending,BuildStatusEnum.Building,BuildStatusEnum.Failed,BuildStatusEnum.Success}]
                              [package ...]

request status of the package

.TP
\fBpackage\fR
filter status by package base

.SH OPTIONS \fI\,'ahriman package-status'\/\fR
.TP
\fB\-\-ahriman\fR
get service status itself

.TP
\fB\-e\fR, \fB\-\-exit\-code\fR
return non\-zero exit status if result is empty

.TP
\fB\-i\fR, \fB\-\-info\fR
show additional package information

.TP
\fB\-s\fR \fI\,{BuildStatusEnum.Unknown,BuildStatusEnum.Pending,BuildStatusEnum.Building,BuildStatusEnum.Failed,BuildStatusEnum.Success}\/\fR, \fB\-\-status\fR \fI\,{BuildStatusEnum.Unknown,BuildStatusEnum.Pending,BuildStatusEnum.Building,BuildStatusEnum.Failed,BuildStatusEnum.Success}\/\fR
filter packages by status

.SH COMMAND \fI\,'ahriman package-status-remove'\/\fR
usage: ahriman package-status-remove [-h] package [package ...]

remove the package from the status page

.TP
\fBpackage\fR
remove specified packages

.SH COMMAND \fI\,'ahriman package-status-update'\/\fR
usage: ahriman package-status-update [-h]
                                     [-s {BuildStatusEnum.Unknown,BuildStatusEnum.Pending,BuildStatusEnum.Building,BuildStatusEnum.Failed,BuildStatusEnum.Success}]
                                     [package ...]

update package status on the status page

.TP
\fBpackage\fR
set status for specified packages. If no packages supplied, service status will be updated

.SH OPTIONS \fI\,'ahriman package-status-update'\/\fR
.TP
\fB\-s\fR \fI\,{BuildStatusEnum.Unknown,BuildStatusEnum.Pending,BuildStatusEnum.Building,BuildStatusEnum.Failed,BuildStatusEnum.Success}\/\fR, \fB\-\-status\fR \fI\,{BuildStatusEnum.Unknown,BuildStatusEnum.Pending,BuildStatusEnum.Building,BuildStatusEnum.Failed,BuildStatusEnum.Success}\/\fR
new status

.SH COMMAND \fI\,'ahriman patch-add'\/\fR
usage: ahriman patch-add [-h] [-t TRACK] package

create or update source patches

.TP
\fBpackage\fR
path to directory with changed files for patch addition/update

.SH OPTIONS \fI\,'ahriman patch-add'\/\fR
.TP
\fB\-t\fR \fI\,TRACK\/\fR, \fB\-\-track\fR \fI\,TRACK\/\fR
files which has to be tracked

.SH COMMAND \fI\,'ahriman patch-list'\/\fR
usage: ahriman patch-list [-h] [-e] [package]

list available patches for the package

.TP
\fBpackage\fR
package base

.SH OPTIONS \fI\,'ahriman patch-list'\/\fR
.TP
\fB\-e\fR, \fB\-\-exit\-code\fR
return non\-zero exit status if result is empty

.SH COMMAND \fI\,'ahriman patch-remove'\/\fR
usage: ahriman patch-remove [-h] package

remove patches for the package

.TP
\fBpackage\fR
package base

.SH COMMAND \fI\,'ahriman repo-backup'\/\fR
usage: ahriman repo-backup [-h] path

backup settings and database

.TP
\fBpath\fR
path of the output archive

.SH COMMAND \fI\,'ahriman repo-check'\/\fR
usage: ahriman repo-check [-h] [-e] [--no-vcs] [package ...]

check for packages updates. Same as update \-\-dry\-run \-\-no\-manual

.TP
\fBpackage\fR
filter check by package base

.SH OPTIONS \fI\,'ahriman repo-check'\/\fR
.TP
\fB\-e\fR, \fB\-\-exit\-code\fR
return non\-zero exit status if result is empty

.TP
\fB\-\-no\-vcs\fR
do not check VCS packages

.SH COMMAND \fI\,'ahriman repo-clean'\/\fR
usage: ahriman repo-clean [-h] [--cache] [--chroot] [--manual] [--packages]

remove local caches

.SH OPTIONS \fI\,'ahriman repo-clean'\/\fR
.TP
\fB\-\-cache\fR
clear directory with package caches

.TP
\fB\-\-chroot\fR
clear build chroot

.TP
\fB\-\-manual\fR
clear manually added packages queue

.TP
\fB\-\-packages\fR
clear directory with built packages

.SH COMMAND \fI\,'ahriman repo-config'\/\fR
usage: ahriman repo-config [-h]

dump configuration for the specified architecture

.SH COMMAND \fI\,'ahriman repo-rebuild'\/\fR
usage: ahriman repo-rebuild [-h] [--depends-on DEPENDS_ON] [--dry-run] [--from-database] [-e]

force rebuild whole repository

.SH OPTIONS \fI\,'ahriman repo-rebuild'\/\fR
.TP
\fB\-\-depends\-on\fR \fI\,DEPENDS_ON\/\fR
only rebuild packages that depend on specified package

.TP
\fB\-\-dry\-run\fR
just perform check for packages without rebuild process itself

.TP
\fB\-\-from\-database\fR
read packages from database instead of filesystem. This feature in particular is required in case if you would like to
restore repository from another repository instance. Note however that in order to restore packages you need to have
original ahriman instance run with web service and have run repo\-update at least once.

.TP
\fB\-e\fR, \fB\-\-exit\-code\fR
return non\-zero exit status if result is empty

.SH COMMAND \fI\,'ahriman repo-remove-unknown'\/\fR
usage: ahriman repo-remove-unknown [-h] [--dry-run] [-i]

remove packages which are missing in AUR and do not have local PKGBUILDs

.SH OPTIONS \fI\,'ahriman repo-remove-unknown'\/\fR
.TP
\fB\-\-dry\-run\fR
just perform check for packages without removal

.TP
\fB\-i\fR, \fB\-\-info\fR
show additional package information

.SH COMMAND \fI\,'ahriman repo-report'\/\fR
usage: ahriman repo-report [-h]

generate repository report according to current settings

.SH COMMAND \fI\,'ahriman repo-restore'\/\fR
usage: ahriman repo-restore [-h] [-o OUTPUT] path

restore settings and database

.TP
\fBpath\fR
path of the input archive

.SH OPTIONS \fI\,'ahriman repo-restore'\/\fR
.TP
\fB\-o\fR \fI\,OUTPUT\/\fR, \fB\-\-output\fR \fI\,OUTPUT\/\fR
root path of the extracted files

.SH COMMAND \fI\,'ahriman repo-setup'\/\fR
usage: ahriman repo-setup [-h] [--build-as-user BUILD_AS_USER] [--build-command BUILD_COMMAND]
                          [--from-configuration FROM_CONFIGURATION] [--no-multilib] --packager PACKAGER --repository
                          REPOSITORY [--sign-key SIGN_KEY]
                          [--sign-target {SignSettings.Disabled,SignSettings.Packages,SignSettings.Repository}]
                          [--web-port WEB_PORT]

create initial service configuration, requires root

.SH OPTIONS \fI\,'ahriman repo-setup'\/\fR
.TP
\fB\-\-build\-as\-user\fR \fI\,BUILD_AS_USER\/\fR
force makepkg user to the specific one

.TP
\fB\-\-build\-command\fR \fI\,BUILD_COMMAND\/\fR
build command prefix

.TP
\fB\-\-from\-configuration\fR \fI\,FROM_CONFIGURATION\/\fR
path to default devtools pacman configuration

.TP
\fB\-\-no\-multilib\fR
do not add multilib repository

.TP
\fB\-\-packager\fR \fI\,PACKAGER\/\fR
packager name and email

.TP
\fB\-\-repository\fR \fI\,REPOSITORY\/\fR
repository name

.TP
\fB\-\-sign\-key\fR \fI\,SIGN_KEY\/\fR
sign key id

.TP
\fB\-\-sign\-target\fR \fI\,{SignSettings.Disabled,SignSettings.Packages,SignSettings.Repository}\/\fR
sign options

.TP
\fB\-\-web\-port\fR \fI\,WEB_PORT\/\fR
port of the web service

.SH COMMAND \fI\,'ahriman repo-sign'\/\fR
usage: ahriman repo-sign [-h] [package ...]

(re\-)sign packages and repository database according to current settings

.TP
\fBpackage\fR
sign only specified packages

.SH COMMAND \fI\,'ahriman repo-status-update'\/\fR
usage: ahriman repo-status-update [-h]
                                  [-s {BuildStatusEnum.Unknown,BuildStatusEnum.Pending,BuildStatusEnum.Building,BuildStatusEnum.Failed,BuildStatusEnum.Success}]

update repository status on the status page

.SH OPTIONS \fI\,'ahriman repo-status-update'\/\fR
.TP
\fB\-s\fR \fI\,{BuildStatusEnum.Unknown,BuildStatusEnum.Pending,BuildStatusEnum.Building,BuildStatusEnum.Failed,BuildStatusEnum.Success}\/\fR, \fB\-\-status\fR \fI\,{BuildStatusEnum.Unknown,BuildStatusEnum.Pending,BuildStatusEnum.Building,BuildStatusEnum.Failed,BuildStatusEnum.Success}\/\fR
new status

.SH COMMAND \fI\,'ahriman repo-sync'\/\fR
usage: ahriman repo-sync [-h]

sync repository files to remote server according to current settings

.SH COMMAND \fI\,'ahriman repo-triggers'\/\fR
usage: ahriman repo-triggers [-h] [trigger ...]

run triggers on empty build result as configured by settings

.TP
\fBtrigger\fR
instead of running all triggers as set by configuration, just process specified ones oin order of metion

.SH COMMAND \fI\,'ahriman repo-update'\/\fR
usage: ahriman repo-update [-h] [--dry-run] [-e] [--no-aur] [--no-local] [--no-manual] [--no-vcs] [package ...]

check for packages updates and run build process if requested

.TP
\fBpackage\fR
filter check by package base

.SH OPTIONS \fI\,'ahriman repo-update'\/\fR
.TP
\fB\-\-dry\-run\fR
just perform check for updates, same as check command

.TP
\fB\-e\fR, \fB\-\-exit\-code\fR
return non\-zero exit status if result is empty

.TP
\fB\-\-no\-aur\fR
do not check for AUR updates. Implies \-\-no\-vcs

.TP
\fB\-\-no\-local\fR
do not check local packages for updates

.TP
\fB\-\-no\-manual\fR
do not include manual updates

.TP
\fB\-\-no\-vcs\fR
do not check VCS packages

.SH COMMAND \fI\,'ahriman user-add'\/\fR
usage: ahriman user-add [-h] [--as-service] [-p PASSWORD]
                        [-r {UserAccess.Unauthorized,UserAccess.Read,UserAccess.Reporter,UserAccess.Full}] [-s]
                        username

update user for web services with the given password and role. In case if password was not entered it will be asked interactively

.TP
\fBusername\fR
username for web service

.SH OPTIONS \fI\,'ahriman user-add'\/\fR
.TP
\fB\-\-as\-service\fR
add user as service user

.TP
\fB\-p\fR \fI\,PASSWORD\/\fR, \fB\-\-password\fR \fI\,PASSWORD\/\fR
user password. Blank password will be treated as empty password, which is in particular must be used for OAuth2
authorization type.

.TP
\fB\-r\fR \fI\,{UserAccess.Unauthorized,UserAccess.Read,UserAccess.Reporter,UserAccess.Full}\/\fR, \fB\-\-role\fR \fI\,{UserAccess.Unauthorized,UserAccess.Read,UserAccess.Reporter,UserAccess.Full}\/\fR
user access level

.TP
\fB\-s\fR, \fB\-\-secure\fR
set file permissions to user\-only

.SH COMMAND \fI\,'ahriman user-list'\/\fR
usage: ahriman user-list [-h] [-e] [-r {UserAccess.Unauthorized,UserAccess.Read,UserAccess.Reporter,UserAccess.Full}]
                         [username]

list users from the user mapping and their roles

.TP
\fBusername\fR
filter users by username

.SH OPTIONS \fI\,'ahriman user-list'\/\fR
.TP
\fB\-e\fR, \fB\-\-exit\-code\fR
return non\-zero exit status if result is empty

.TP
\fB\-r\fR \fI\,{UserAccess.Unauthorized,UserAccess.Read,UserAccess.Reporter,UserAccess.Full}\/\fR, \fB\-\-role\fR \fI\,{UserAccess.Unauthorized,UserAccess.Read,UserAccess.Reporter,UserAccess.Full}\/\fR
filter users by role

.SH COMMAND \fI\,'ahriman user-remove'\/\fR
usage: ahriman user-remove [-h] [-s] username

remove user from the user mapping and update the configuration

.TP
\fBusername\fR
username for web service

.SH OPTIONS \fI\,'ahriman user-remove'\/\fR
.TP
\fB\-s\fR, \fB\-\-secure\fR
set file permissions to user\-only

.SH COMMAND \fI\,'ahriman web'\/\fR
usage: ahriman web [-h]

start web server

.SH COMMENTS
Argument list can also be read from file by using @ prefix.

.SH AUTHORS
.nf
ahriman team
.fi.nf

.fi

.SH DISTRIBUTION
The latest version of ahriman may be downloaded from
.UR https://github.com/arcan1s/ahriman
.UE
