name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run check and tests in archlinux container
        run: |
          docker run \
          -v  ${{ github.workspace }}:/build -w /build \
          archlinux:latest \
          /bin/bash -c "pacman --noconfirm -Syu base-devel python python-pip && \
          pip install -e .[web] && \
          pip install -e .[check] && \
          pip install -e .[s3] && \
          pip install -e .[test] && \
          make check tests"
