name: setup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-setup:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup the service in arch linux container
        run: |
          docker run --privileged \
          -v  ${{ github.workspace }}:/build -w /build \
          archlinux:latest \
          .github/workflows/setup.sh
