name: Setup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-setup-minimal:

    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      volumes:
        - ${{ github.workspace }}:/build
      options: --privileged -w /build

    steps:
      - uses: actions/checkout@v3

      - name: Setup the minimal service in arch linux container
        run: .github/workflows/setup.sh minimal

  run-setup:

    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      volumes:
        - ${{ github.workspace }}:/build
      options: --privileged -w /build

    steps:
      - uses: actions/checkout@v3

      - name: Setup the service in arch linux container
        run: .github/workflows/setup.sh
