name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 1 0 * * *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-tests:

    runs-on: ubuntu-latest

    container:
      image: archlinux:base
      options: -w /build
      volumes:
        - ${{ github.workspace }}:/build

    steps:
      - run: pacman --noconfirm -Syu base-devel git python-tox

      - run: git config --global --add safe.directory *

      - uses: actions/checkout@v4

      - name: Run check and tests
        run: tox

      - name: Generate documentation and check if there are untracked changes
        run: |
          tox -e docs
          [ -z "$(git status --porcelain docs/*.rst)" ]
