name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      volumes:
        - ${{ github.workspace }}:/build
      options: -w /build

    steps:
      - uses: actions/checkout@v3

      - name: Run check and tests in arch linux container
        run: .github/workflows/tests.sh
