[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "ahriman-triggers"
dependencies = [
    "ahriman-core",
]
description = "ArcH linux ReposItory MANager, additional extensions"
dynamic = [
    "version",
]
requires-python = ">=3.14"

[tool.hatch.build.targets.wheel]
packages = [
    "src/ahriman",
]

[tool.hatch.build.targets.wheel.shared-data]
"package/share" = "share"

[tool.hatch.version]
path = "../ahriman-core/src/ahriman/__init__.py"
